### PR TITLE
Defragment framework interfaces into context based calls

### PR DESCRIPTION
**Pull request by fengjingchao**
Implemented #107

### CODE REVIEW

**Comment by fengjingchao** [comment]
@xiaoyunwu @xiang90 
Please review and give feedback on this.

**Comment by fengjingchao** [comment]
An alternative to the name "context" could be "scope". Tell me if you like either.

**Comment by xiaoyunwu** [comment]
LGTM, except one little thing. createContext, or just Context should be fine. Ctx as method name seems a bit odd. 

Thanks.

**Comment by fengjingchao** [comment]
"createContext" sounds good to me. Fixed!

**Comment by xiaoyunwu** [comment]
LGTM.

**Pull request merged**
